accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

pricolweb/urls.py
from django.contrib.auth import urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(urls)),
    path('accounts/', include('accounts.urls')),
    path('', include('status.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

status/urls.py
from django.urls import path
from .views import HomePageView, MachinePageView, MachineDetailView, NewStatusView, UpdateStatusView, \
    DeleteStatusView, DocumentListView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('machines/', MachinePageView.as_view(), name='machines'),
    path('machine/<int:pk>/', MachineDetailView.as_view(), name='machine_detail'),
    path('new/', NewStatusView.as_view(), name='new_status'),
    path('machine/<int:pk>/update/', UpdateStatusView.as_view(), name='update_status'),
    path('machine/<int:pk>/delete/', DeleteStatusView.as_view(), name='delete_status'),
    path('machines/documents/', DocumentListView.as_view(), name='documents'),
]

accounts/models.py
from django.db import models

# Create your models here.

status/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Machine(models.Model):
    name = models.CharField(max_length=50)
    manufacture_year = models.DateField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home')


class Status(models.Model):
    working_choices = [('Yes', 'Yes'),
                       ('No', 'No')]
    machine = models.ForeignKey(Machine, on_delete=models.SET_NULL, null=True)
    is_working = models.CharField(max_length=3, choices=working_choices)
    description = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    document = models.FileField(upload_to='documents/', null=True, blank=True)
    document_name = models.CharField(max_length=50, blank=True)

    def __str__(self):
        time = str(self.time)[:19]
        name = "{}-{}".format(self.machine, time)
        return name

    def get_absolute_url(self):
        return reverse('home')

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy
# Create your views here.


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

status/views.py
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Machine, Status
from django.urls import reverse_lazy

# Create your views here.


class HomePageView(ListView):
    model = Status
    template_name = 'home.html'


class MachinePageView(ListView):
    model = Machine
    template_name = 'machines.html'


class MachineDetailView(DetailView):
    model = Machine
    template_name = 'machine_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["status"] = Status.objects.all()
        return context


class NewStatusView(CreateView):
    model = Status
    template_name = "new.html"
    fields = ['machine', 'is_working', 'description', 'document', 'document_name']


class UpdateStatusView(UpdateView):
    model = Status
    template_name = "update.html"
    fields = ['machine', 'is_working', 'description', 'document', 'document_name']


class DeleteStatusView(DeleteView):
    model = Status
    template_name = 'delete_status.html'
    success_url = reverse_lazy("home")

class DocumentListView(ListView):
    model = Status
    template_name = 'documents_view.html'

templates/base.html
{% load static %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"></head>

{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="{% static 'logo-img.png' %}" alt="" width="120" height="24" class="d-inline-block align-text-top">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Status</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'machines' %}">Machines</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'documents' %}">Documents</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'new_status' %}">New Status</a>
        </li>
      </ul>
      <span class="navbar-text">
        {% if user.is_authenticated %}
          <button type="button" class="btn btn-outline-dark">{{ user.username }}</button>
          <a href="{% url 'logout' %}" class="btn btn-danger" tabindex="-1" role="button" aria-disabled="true">LogOut</a>
        {% else %}
          <a href="{% url 'login' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">LogIn</a>
          <a href="{% url 'signup' %}" class="btn btn-warning" tabindex="-1" role="button" aria-disabled="true">SignUp</a>
        {% endif %}
      </span>
    </div>
  </div>
</nav>
{% endif %}

<body>
{% if user.is_authenticated %}
    {% block content %}
    {% endblock %}
{% else %}
    <div class="position-absolute top-50 start-50 translate-middle">
      <p class="fs-1">WELCOME TO PRICOL</p>
      <a href="{% url 'login' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">LogIn</a>
      <a href="{% url 'signup' %}" class="btn btn-warning" tabindex="-1" role="button" aria-disabled="true">SignUp</a>
    </div>
{% endif %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

templates/delete_status.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="position-absolute top-50 start-50 translate-middle">
<form action="" method="post">
    {% csrf_token %}
    <p class="fs-2">Are you sure, you wanna delete?</p>
    <input type="submit" class="btn btn-danger" value="Delete">
</form>
</div>
{% endblock %}

templates/documents_view.html
{% extends 'base.html' %}
{% block content %}
{% for status in status_list %}
<ul>
    <p>{% if status.document_name %}
        <a href="{{ status.document.url }}">{{ status.document_name }}</a>
        {% else %}
        <a href="{{ status.document.url }}">Unnamed</a>
        {% endif %} - {{status.machine }} - {{ status.time }} </p>
</ul>
{%endfor%}
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
{% for status in status_list %}
<ul>
    <br>
    <h4>{{ status.machine }}</h4>
    <p>{{ status.time }}</p>
    <p>WORKING - {{ status.is_working }}</p>
    <p>{{ status.description }}</p>
    <p>{{ status.username }}</p>
    <p>{% if status.document %}
        {% if status.document_name %}
        <a href="{{ status.document.url }}">{{ status.document_name }}</a>
        {% else %}
        <a href="{{ status.document.url }}">Unnamed</a>
        {% endif %}
    {% endif %}</p>
    <br>
</ul>
{%endfor%}
{% endblock %}

templates/machine_detail.html
{% extends 'base.html' %}
{% block content %}
<br>
<h2>{{ object.name }}</h2>
{% for status in status %}
    {% if status.machine == machine %}
    <ul>
    <p>{{status.time}}</p>
    <p>WORKING - {{ status.is_working }}</p>
    <p>{{ status.description }}</p>
    <p>{% if status.document %}
        {% if status.document_name %}
        <a href="{{ status.document.url }}">{{ status.document_name }}</a>
        {% else %}
        <a href="{{ status.document.url }}">Unnamed</a>
        {% endif %}
    {% endif %}</p>
    <a href="{% url 'update_status' status.pk%}" class="btn btn-secondary" tabindex="-1" role="button" aria-disabled="true">
        Update</a>
    <a href="{% url 'delete_status' status.pk%}" class="btn btn-danger" tabindex="-1" role="button" aria-disabled="true">
        Delete</a>
    <hr>
    {% endif %}
</ul>
{% endfor %}
{% endblock %}

templates/machines.html
{% extends 'base.html' %}
{% block content %}
<br>
{% for machine in machine_list%}
    <ul>
        <p class="fs-6"><a href="{% url 'machine_detail' machine.pk%}" class="btn btn-link btn-lg" tabindex="-1" role="button" aria-disabled="true">
            {{ machine.name }}</a> {{ machine.manufacture_year }}</p>
    </ul>
{% endfor %}
{% endblock %}

templates/new.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="position-absolute top-50 start-50 translate-middle">
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" class="btn btn-success" value="Save">
</form>
</div>
{% endblock %}

templates/signup.html
{% load static %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"></head>

<body>
    {% load crispy_forms_tags %}
    <div class="position-absolute top-50 start-50 translate-middle">
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-warning">SignUp</button>
    </form>
    <p class="fs-6 fst-italic">Already have an account?</p>
    <a href="{% url 'login' %}" class="btn btn-info btn-sm" tabindex="-1" role="button" aria-disabled="true">LogIn</a>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

templates/update.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="position-absolute top-50 start-50 translate-middle">
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" class="btn btn-secondary" value="Update">
</form>
</div>
{% endblock %}